"""empty message

Revision ID: 2cef754f1b4d
Revises: 0ca18f38df2c
Create Date: 2023-07-16 20:13:45.797445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cef754f1b4d'
down_revision = '0ca18f38df2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('chapter_pres',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('org_staff',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('org_staff',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('chapter_pres',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
