"""empty message

Revision ID: c014aa507844
Revises: 290c27b45b73
Create Date: 2023-07-23 03:50:01.111649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c014aa507844'
down_revision = '290c27b45b73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('chapter',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('chapter',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
        batch_op.alter_column('grade',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
